-- Preparación para un proyecto Supabase nuevo. Aún no aplicada.
begin;
create table public.catalog_admins (
    user_id uuid primary key references auth.users(id) on delete cascade
);
alter table public.catalog_admins enable row level security;
revoke all on public.catalog_admins from anon, authenticated;
grant select on public.catalog_admins to authenticated;
create policy "Read own membership" on public.catalog_admins
    for select to authenticated using (user_id = (select auth.uid()));

create table public.products (
    id bigint generated by default as identity primary key,
    name text,
    brand text not null,
    category text not null check (category in ('Hoodies','T-Shirts','Sueter','Pants','Shorts','Accessories')),
    model text not null,
    collection text,
    color text,
    material text,
    finish text,
    description text,
    price numeric(12,2) check (price >= 0),
    featured boolean not null default false,
    published boolean not null default false,
    images text[] not null default '{}',
    created_at timestamptz not null default now()
);
create table public.product_variants (
    id bigint generated by default as identity primary key,
    product_id bigint not null references public.products(id) on delete cascade,
    size text not null,
    stock integer not null default 0 check (stock >= 0),
    unique(product_id, size)
);
alter table public.products enable row level security;
alter table public.product_variants enable row level security;
revoke all on public.products, public.product_variants from anon, authenticated;
grant select on public.products, public.product_variants to anon, authenticated;
grant insert, update, delete on public.products, public.product_variants to authenticated;
grant usage on sequence public.products_id_seq, public.product_variants_id_seq to authenticated;

create policy "Published catalog" on public.products for select to anon, authenticated using (published);
create policy "Published variants" on public.product_variants for select to anon, authenticated
    using (exists (select 1 from public.products p where p.id = product_id and p.published));
create policy "Admin products" on public.products for all to authenticated
    using (exists (select 1 from public.catalog_admins where user_id = (select auth.uid())))
    with check (exists (select 1 from public.catalog_admins where user_id = (select auth.uid())));
create policy "Admin variants" on public.product_variants for all to authenticated
    using (exists (select 1 from public.catalog_admins where user_id = (select auth.uid())))
    with check (exists (select 1 from public.catalog_admins where user_id = (select auth.uid())));
commit;
