import assert from 'node:assert/strict';
import {validateImage,objectPath,uploadImage,deleteImage,MAX_BYTES} from './js/media-data.js';
const bytes=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=','base64');
const png=new File([bytes],'same.png',{type:'image/png'});
assert.equal(await validateImage(png),'png');
await assert.rejects(validateImage(new File(['no'],'invalid.png',{type:'image/png'})),/contenido/);
await assert.rejects(validateImage(new File(['x'],'file.txt',{type:'text/plain'})),/JPEG/);
await assert.rejects(validateImage(new File([new Uint8Array(MAX_BYTES+1)],'large.png',{type:'image/png'})),/5 MB/);
const image={id:100,bucket_id:'product-images',path:'products/46/00000000-0000-0000-0000-000000000001.png'};
assert.equal(objectPath(image,46),image.path);
assert.throws(()=>objectPath(image,2),/ajena/);
const calls=[];let failed=true;
const client={rpc:async(name,args)=>{calls.push(args.p_action);return {data:image};},storage:{from:()=>({upload:async()=>({error:failed?{}:null}),remove:async()=>({error:failed?{}:null})})}};
await assert.rejects(uploadImage(client,46,png),/pendiente/);
assert.deepEqual(calls,['reserve']);
calls.length=0;failed=false;await uploadImage(client,46,png);assert.deepEqual(calls,['reserve','complete']);
calls.length=0;failed=true;await assert.rejects(deleteImage(client,46,image),/pendiente/);assert.deepEqual(calls,['begin_image_delete']);
calls.length=0;failed=false;await deleteImage(client,46,image);assert.deepEqual(calls,['begin_image_delete','finish_image_delete']);
console.log('PASS: formatos/tamaño, pertenencia, subida fallida no se publica, eliminación fallida no borra referencia, reintento.');
