-- Nueva instalación solamente. No ejecutar junto con ../001_catalog.sql.
begin;

create table public.catalog_admins (
  user_id uuid primary key references auth.users(id) on delete cascade
);
alter table public.catalog_admins enable row level security;
revoke all on public.catalog_admins from PUBLIC, anon, authenticated;
grant select on public.catalog_admins to authenticated;
create policy own_membership on public.catalog_admins for select to authenticated
  using (user_id = (select auth.uid()));

create function public.is_catalog_admin() returns boolean
language sql stable security definer set search_path = '' as $$
  select exists (select 1 from public.catalog_admins where user_id = (select auth.uid()));
$$;
revoke all on function public.is_catalog_admin() from public;
grant execute on function public.is_catalog_admin() to anon, authenticated;

create table public.brands (
  id text primary key, name text not null unique, position integer not null default 0
);
create table public.categories (
  id text primary key, name text not null, position integer not null default 0
);
create table public.collections (
  id text primary key, name text not null,
  discount_enabled boolean not null default true,
  discount_amount numeric(12,2) not null default 150 check (discount_amount >= 0),
  minimum_pieces integer not null default 2 check (minimum_pieces >= 2)
);
create table public.products (
  id bigint generated by default as identity primary key,
  name text not null, brand_id text not null references public.brands(id),
  category_id text not null references public.categories(id),
  collection_id text references public.collections(id),
  model text, color text, material text, finish text, description text,
  price numeric(12,2) check (price >= 0),
  featured boolean not null default false,
  published boolean not null default false,
  position integer not null default 0,
  requires_size boolean not null default true,
  max_quantity integer not null default 5 check (max_quantity between 1 and 5),
  created_at timestamptz not null default now()
);
create table public.product_variants (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  size text not null check (length(trim(size)) > 0),
  stock integer check (stock >= 0),
  position integer not null default 0,
  unique (product_id, size)
);
create table public.product_images (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  path text not null check (length(trim(path)) > 0),
  alt text not null default '', position integer not null check (position >= 0),
  unique (product_id, position)
);
create index products_brand_idx on public.products(brand_id);
create index products_category_idx on public.products(category_id);
create index products_collection_idx on public.products(collection_id);
create index products_public_order_idx on public.products(published, position);

-- Sin permisos administrativos basados en metadata editable por el usuario.
do $$
declare t text;
begin
  foreach t in array array['brands','categories','collections','products','product_variants','product_images'] loop
    execute format('alter table public.%I enable row level security', t);
    execute format('revoke all on public.%I from PUBLIC, anon, authenticated', t);
    execute format('grant select on public.%I to anon, authenticated', t);
    execute format('grant insert, update, delete on public.%I to authenticated', t);
    execute format('create policy admin_access on public.%I for all to authenticated using ((select public.is_catalog_admin())) with check ((select public.is_catalog_admin()))', t);
  end loop;
end $$;
create policy public_products on public.products for select to anon, authenticated using (published);
create policy public_variants on public.product_variants for select to anon, authenticated
  using (exists (select 1 from public.products p where p.id = product_id and p.published));
create policy public_images on public.product_images for select to anon, authenticated
  using (exists (select 1 from public.products p where p.id = product_id and p.published));
-- Solo taxonomías relacionadas con al menos un producto publicado.
create policy public_brands on public.brands for select to anon, authenticated
  using (exists (select 1 from public.products p where p.brand_id = brands.id and p.published));
create policy public_categories on public.categories for select to anon, authenticated
  using (exists (select 1 from public.products p where p.category_id = categories.id and p.published));
create policy public_collections on public.collections for select to anon, authenticated
  using (exists (select 1 from public.products p where p.collection_id = collections.id and p.published));
revoke all on sequence public.products_id_seq, public.product_variants_id_seq, public.product_images_id_seq from PUBLIC, anon, authenticated;
grant usage on sequence public.products_id_seq, public.product_variants_id_seq, public.product_images_id_seq to authenticated;

comment on column public.product_variants.stock is 'NULL: sin inventario registrado; 0: agotado. No convertir NULL a cero.';
comment on table public.collections is 'Descuento fijo una vez por colección al alcanzar minimum_pieces, incluso varias piezas del mismo modelo. Total mínimo cero.';
commit;
