-- Snapshot del catálogo actual. Ejecutar una sola vez después del esquema.
begin;
insert into public.brands (id, name, position) values
('Essentials', 'Essentials', 0),
('Van Cleef', 'Van Cleef', 1),
('Alo', 'Alo', 2);
insert into public.categories (id, name, position) values
('Hoodies', 'Hoodies', 0),
('T-Shirts', 'Playeras', 1),
('Pants', 'Pants', 2),
('Shorts', 'Shorts', 3),
('Sueter', 'Sueter', 4),
('Accessories', 'Accesorios', 5);
insert into public.collections (id, name) values
('strech-lim', 'Strech Lim'),
('light-oatmeal', 'Light Oatmeal'),
('dark-oatmeal', 'Dark Oatmeal'),
('fleece-black', 'Fleece Black'),
('desert-sand', 'Desert Sand'),
('dusty-beige', 'Dusty Beige'),
('bright-white', 'Bright White'),
('desert-taupe', 'Desert Taupe'),
('light-health', 'Light Health');
insert into public.products (id, name, brand_id, category_id, collection_id, model, color, material, finish, description, price, featured, published, position, requires_size) values
(1, 'Essentials Hoodie Strech Lim', 'Essentials', 'Hoodies', 'strech-lim', 'Strech Lim', 'Black', null, null, null, 999, true, false, 0, true),
(2, 'Essentials Hoodie Light Oatmeal', 'Essentials', 'Hoodies', 'light-oatmeal', 'Light Oatmeal', 'Light Oatmeal', 'Pendiente', null, '...', 999, true, false, 1, true),
(3, 'Essentials Hoodie Dark Oatmeal', 'Essentials', 'Hoodies', 'dark-oatmeal', 'Dark Oatmeal', 'Dark Oatmeal', null, null, null, 999, false, false, 2, true),
(4, 'Essentials Hoodie Fleece Black', 'Essentials', 'Hoodies', 'fleece-black', 'Fleece Black', 'Black', null, null, null, 1199, false, false, 3, true),
(5, 'Essentials Hoodie Desert Sand', 'Essentials', 'Hoodies', 'desert-sand', 'Desert Sand', 'Desert Sand', null, null, null, 1199, false, false, 4, true),
(6, 'Essentials Hoodie Dusty Beige', 'Essentials', 'Hoodies', 'dusty-beige', 'Dusty Beige', 'Dusty Beige', null, null, null, 1199, false, false, 5, true),
(8, 'Essentials T-shirt Light Oatmeal', 'Essentials', 'T-Shirts', 'light-oatmeal', 'Light Oatmeal', 'Light Oatmeal', null, null, null, 899, false, false, 6, true),
(9, 'Essentials T-shirt Bright White', 'Essentials', 'T-Shirts', 'bright-white', 'Bright White', 'White', null, null, null, 899, true, false, 7, true),
(10, 'Essentials T-shirt Fleece Black', 'Essentials', 'T-Shirts', 'fleece-black', 'Fleece Black', 'Black', null, null, null, 899, false, false, 8, true),
(11, 'Essentials T-shirt Dusty Beige', 'Essentials', 'T-Shirts', 'dusty-beige', 'Dusty Beige', 'Dusty Beige', null, null, null, 999, false, false, 9, true),
(12, 'Essentials Pants Dark Oatmeal', 'Essentials', 'Pants', 'dark-oatmeal', 'Dark Oatmeal', 'Dark Oatmeal', null, null, null, 999, false, false, 10, true),
(14, 'Essentials Pants Dusty Beige', 'Essentials', 'Pants', 'dusty-beige', 'Dusty Beige', 'Dusty Beige', null, null, null, 1199, false, false, 11, true),
(15, 'Essentials Pants Fleece Black', 'Essentials', 'Pants', 'fleece-black', 'Fleece Black', 'Black', null, null, null, 1199, false, false, 12, true),
(16, 'Essentials Short Desert Taupe', 'Essentials', 'Shorts', 'desert-taupe', 'Desert Taupe', 'Desert Taupe', null, null, null, 899, false, false, 13, true),
(22, 'Essentials Short Fleece Black', 'Essentials', 'Shorts', 'fleece-black', 'Fleece Black', null, null, null, null, 899, false, false, 14, true),
(23, 'Essentials Short Dusty Beige', 'Essentials', 'Shorts', 'dusty-beige', 'Dusty Beige', null, null, null, null, 899, false, false, 15, true),
(24, 'Essentials Short Strech Lim', 'Essentials', 'Shorts', 'strech-lim', 'Strech Lim', null, null, null, null, 899, false, false, 16, true),
(25, 'Essentials Pants Light Health', 'Essentials', 'Pants', 'light-health', 'Light Health', null, null, null, null, 1199, false, false, 17, true),
(26, 'Alo Suéter Negro', 'Alo', 'Sueter', null, 'Negro', null, null, null, null, 1399, false, false, 18, true),
(27, 'Alo Suéter Gris', 'Alo', 'Sueter', null, 'Gris', null, null, null, null, 1399, false, false, 19, true),
(28, 'Alo Suéter Azul', 'Alo', 'Sueter', null, 'Azul', null, null, null, null, 1399, false, false, 20, true),
(29, 'Alo Hoodie Azul', 'Alo', 'Hoodies', null, 'Azul', null, null, null, null, 1399, false, false, 21, true),
(30, 'Alo Hoodie Café', 'Alo', 'Hoodies', null, 'Café', null, null, null, null, 1399, false, false, 22, true),
(31, 'Alo Hoodie Negro', 'Alo', 'Hoodies', null, 'Negro', null, null, null, null, 1399, false, false, 23, true),
(32, 'Van Cleef Pulsera Oro-Negro', 'Van Cleef', 'Accessories', null, 'Oro-Negro', null, 'Baño de oro', null, 'Pulsera bañada en oro, con detalles en color negro.', 1699, false, false, 24, false),
(33, 'Van Cleef Pulsera Oro-Rosa', 'Van Cleef', 'Accessories', null, 'Oro-Rosa', null, 'Baño de oro', null, 'Pulsera bañada en oro, con detalles en color rosa.', 1699, false, false, 25, false),
(34, 'Van Cleef Pulsera Oro-Azul', 'Van Cleef', 'Accessories', null, 'Oro-Azul', null, 'Baño de oro', null, 'Pulsera bañada en oro, con detalles en color azul.', 1699, false, false, 26, false),
(35, 'Van Cleef Pulsera Oro-Verde', 'Van Cleef', 'Accessories', null, 'Oro-Verde', null, 'Baño de oro', null, 'Pulsera bañada en oro, con detalles en color verde.', 1699, false, false, 27, false),
(37, 'Van Cleef Pulsera Plata-Blanco/Negro', 'Van Cleef', 'Accessories', null, 'Plata-Blanco/Negro', null, 'Plata', null, 'Pulsera hecha de plata, con detalles en color blanco y negro.', 1699, false, false, 28, false),
(38, 'Van Cleef Pulsera Plata-Blanco/Azul', 'Van Cleef', 'Accessories', null, 'Plata-Blanco/Azul', null, 'Plata', null, 'Pulsera hecha de plata, con detalles en color blanco y azul.', 1699, false, false, 29, false),
(39, 'Van Cleef Pulsera Plata/Azul Celeste', 'Van Cleef', 'Accessories', null, 'Plata/Azul Celeste', null, 'Plata', null, 'Pulsera hecha de plata, con detalles en color azul celeste.', 1699, false, false, 30, false),
(40, 'Van Cleef Pulsera Plata/Azul Marino', 'Van Cleef', 'Accessories', null, 'Plata/Azul Marino', null, 'Plata', null, 'Pulsera hecha de plata, con detalles en color azul marino.', 1699, false, false, 31, false);
insert into public.product_variants (product_id, size, stock, position) values
(1, 'S', null, 0),
(1, 'M', null, 1),
(1, 'L', null, 2),
(1, 'XL', null, 3),
(2, 'S', 1, 0),
(2, 'M', 2, 1),
(2, 'L', 0, 2),
(2, 'XL', 1, 3),
(3, 'S', null, 0),
(3, 'M', null, 1),
(3, 'L', null, 2),
(3, 'XL', null, 3),
(4, 'S', null, 0),
(4, 'M', null, 1),
(4, 'L', null, 2),
(4, 'XL', null, 3),
(5, 'S', null, 0),
(5, 'M', null, 1),
(5, 'L', null, 2),
(5, 'XL', null, 3),
(6, 'S', null, 0),
(6, 'M', null, 1),
(6, 'L', null, 2),
(6, 'XL', null, 3),
(8, 'S', null, 0),
(8, 'M', null, 1),
(8, 'L', null, 2),
(8, 'XL', null, 3),
(9, 'S', null, 0),
(9, 'M', null, 1),
(9, 'L', null, 2),
(9, 'XL', null, 3),
(10, 'S', null, 0),
(10, 'M', null, 1),
(10, 'L', null, 2),
(10, 'XL', null, 3),
(11, 'S', null, 0),
(11, 'M', null, 1),
(11, 'L', null, 2),
(11, 'XL', null, 3),
(12, 'S', null, 0),
(12, 'M', null, 1),
(12, 'L', null, 2),
(12, 'XL', null, 3),
(14, 'S', null, 0),
(14, 'M', null, 1),
(14, 'L', null, 2),
(14, 'XL', null, 3),
(15, 'S', null, 0),
(15, 'M', null, 1),
(15, 'L', null, 2),
(15, 'XL', null, 3),
(16, 'S', null, 0),
(16, 'M', null, 1),
(16, 'L', null, 2),
(16, 'XL', null, 3),
(22, 'S', null, 0),
(22, 'M', null, 1),
(22, 'L', null, 2),
(22, 'XL', null, 3),
(23, 'S', null, 0),
(23, 'M', null, 1),
(23, 'L', null, 2),
(23, 'XL', null, 3),
(24, 'S', null, 0),
(24, 'M', null, 1),
(24, 'L', null, 2),
(24, 'XL', null, 3),
(25, 'S', null, 0),
(25, 'M', null, 1),
(25, 'L', null, 2),
(25, 'XL', null, 3),
(26, 'S', null, 0),
(26, 'M', null, 1),
(26, 'L', null, 2),
(26, 'XL', null, 3),
(27, 'S', null, 0),
(27, 'M', null, 1),
(27, 'L', null, 2),
(27, 'XL', null, 3),
(28, 'S', null, 0),
(28, 'M', null, 1),
(28, 'L', null, 2),
(28, 'XL', null, 3),
(29, 'S', null, 0),
(29, 'M', null, 1),
(29, 'L', null, 2),
(29, 'XL', null, 3),
(30, 'S', null, 0),
(30, 'M', null, 1),
(30, 'L', null, 2),
(30, 'XL', null, 3),
(31, 'S', null, 0),
(31, 'M', null, 1),
(31, 'L', null, 2),
(31, 'XL', null, 3),
(32, 'Única', null, 0),
(33, 'Única', null, 0),
(34, 'Única', null, 0),
(35, 'Única', null, 0),
(37, 'Única', null, 0),
(38, 'Única', null, 0),
(39, 'Única', null, 0),
(40, 'Única', null, 0);
insert into public.product_images (product_id, path, alt, position) values
(1, 'assets/img/catalogo/essentials-hoodie-strech-lim.png', 'Essentials Hoodie Strech Lim', 0),
(2, 'assets/img/catalogo/essentials-hoodie-light-oatmeal.png', 'Essentials Hoodie Light Oatmeal', 0),
(3, 'assets/img/catalogo/essentials-hoodie-dark-oatmeal.png', 'Essentials Hoodie Dark Oatmeal', 0),
(4, 'assets/img/catalogo/essentials-hoodie-fleece-black.png', 'Essentials Hoodie Fleece Black', 0),
(5, 'assets/img/catalogo/essentials-hoodie-desert-sand.png', 'Essentials Hoodie Desert Sand', 0),
(6, 'assets/img/catalogo/essentials-hoodie-dusty-beige.png', 'Essentials Hoodie Dusty Beige', 0),
(8, 'assets/img/catalogo/essentials-t-shirt-light-oatmeal.png', 'Essentials T-shirt Light Oatmeal', 0),
(9, 'assets/img/catalogo/essentials-t-shirt-bright-white.jpg', 'Essentials T-shirt Bright White', 0),
(10, 'assets/img/catalogo/essentials-t-shirt-fleece-black.jpg', 'Essentials T-shirt Fleece Black', 0),
(11, 'assets/img/catalogo/essentials-t-shirt-dusty-beige.png', 'Essentials T-shirt Dusty Beige', 0),
(12, 'assets/img/catalogo/essentials-pants-dark-oatmeal.jpg', 'Essentials Pants Dark Oatmeal', 0),
(14, 'assets/img/catalogo/essentials-pants-dusty-beige.jpg', 'Essentials Pants Dusty Beige', 0),
(15, 'assets/img/catalogo/essentials-pants-fleece-black.jpg', 'Essentials Pants Fleece Black', 0),
(16, 'assets/img/catalogo/essentials-short-desert-taupe.jpg', 'Essentials Short Desert Taupe', 0),
(22, 'assets/img/catalogo/essentials-short-fleece-black.png', 'Essentials Short Fleece Black', 0),
(23, 'assets/img/catalogo/essentials-short-dusty-beige.jpg', 'Essentials Short Dusty Beige', 0),
(24, 'assets/img/catalogo/essentials-short-strech-lim.jpg', 'Essentials Short Strech Lim', 0),
(25, 'assets/img/catalogo/essentials-pants-light-health.png', 'Essentials Pants Light Health', 0),
(26, 'assets/img/catalogo/alo-sueter-negro.png', 'Alo Suéter Negro', 0),
(27, 'assets/img/catalogo/alo-sueter-gris.png', 'Alo Suéter Gris', 0),
(28, 'assets/img/catalogo/alo-sueter-azul.png', 'Alo Suéter Azul', 0),
(29, 'assets/img/catalogo/alo-hoodie-azul.png', 'Alo Hoodie Azul', 0),
(30, 'assets/img/catalogo/alo-hoodie-cafe.png', 'Alo Hoodie Café', 0),
(31, 'assets/img/catalogo/alo-hoodie-negro.png', 'Alo Hoodie Negro', 0),
(32, 'assets/img/catalogo/van-cleef-pulsera-dorado-negro.png', 'Van Cleef Pulsera Oro-Negro', 0),
(33, 'assets/img/catalogo/van-cleef-pulsera-dorado-rosa.png', 'Van Cleef Pulsera Oro-Rosa', 0),
(34, 'assets/img/catalogo/van-cleef-pulsera-dorado-azul.png', 'Van Cleef Pulsera Oro-Azul', 0),
(35, 'assets/img/catalogo/van-cleef-pulsera-dorado-verde-1.png', 'Van Cleef Pulsera Oro-Verde', 0),
(35, 'assets/img/catalogo/van-cleef-pulsera-dorado-verde-2.png', 'Van Cleef Pulsera Oro-Verde', 1),
(37, 'assets/img/catalogo/van-cleef-pulsera-blanco-negro.png', 'Van Cleef Pulsera Plata-Blanco/Negro', 0),
(38, 'assets/img/catalogo/van-cleef-pulsera-blanco-azul.png', 'Van Cleef Pulsera Plata-Blanco/Azul', 0),
(39, 'assets/img/catalogo/van-cleef-pulsera-azul-bajito.png', 'Van Cleef Pulsera Plata/Azul Celeste', 0),
(40, 'assets/img/catalogo/van-cleef-pulsera-azul-marino.png', 'Van Cleef Pulsera Plata/Azul Marino', 0);
select setval(pg_get_serial_sequence('public.products', 'id'), (select max(id) from public.products), true);
commit;
